# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171212_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
