# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171212_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
