# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('home', '0004_auto_20171212_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
